### ISSUE TITLE
Issues yang ada di app ( sebagai notes aja )

### ISSUE THREAD

**Issue by miqbal-dev** [fajaaro/mt-test#1]
# Error 1
username function di "AuthenticatesUsers" traits belum di override

https://github.com/fajaaro/mt-test/blob/12405acb5a6e1e48021e115a3af0c7dec187bb1f/app/Http/Controllers/Auth/LoginController.php#L22
[](url)
karna by default dia refer ke 'email'
```php
/**
* Get the login username to be used by the controller.
*
* @return string
*/
public function username()
{
    // ini perlu di override ke identifier yang kita pake di controller 'LoginController' yaitu 'username'
    return 'email';
}
```

# Error 2

![image](https://github.com/fajaaro/mt-test/assets/57672230/0d735efb-b41b-4880-bec7-967584111c17)

```php
class AbsenceHelper
{
    public static function getAbsenceReport($absence)
    {
        // dibagian ini harus ada default value ketika tidak ada value sama sekali, misalnya 'now()'
        $absenceDate = $absence->created_at;
        
        // contoh
        $absenceDate = $absence->created_at ?? now();
    .....
```

itu aja si sejauh ini, thank you.

**Comment by fajaaro** [comment]
Izin mas, kedua error tersebut sudah diperbaiki dan sudah di-commit.

**Comment by miqbal-dev** [comment]
okey siap makasih ya @fajaaro
